export enum CacheKeys {
  Users = 'users',
  Transactions = 'transactions',
  Galleries = 'galleries',
  GalleryItems = 'galleryItems',
  Addresses = 'addresses',
  Attributes = 'attributes',
  AttributeValues = 'attributeValues',
  Products = 'products',
  ProductVariants = 'productVariants',
  Categories = 'categories',
  Comments = 'comments',
  Orders = 'orders',
  Blogs = 'blogs',
  Tags = 'tags',
  Shippings = 'shippings',
  Pages = 'pages',
  Contact = 'contact',
}
