---
deployment:
  tasks:
    - export DEPLOYPATH=/home/umwrtkni/api.shopinka
    - find "$DEPLOYPATH" -mindepth 1 ! -name 'node_modules' ! -path "$DEPLOYPATH/node_modules/*" -exec rm -rf {} +
    - cp -r * $DEPLOYPATH
    - cd $DEPLOYPATH
