export enum RefundPaymentReason {
    CUSTOMER_REQUEST = 'CUSTOMER_REQUEST',
    DUPLICATE_TRANSACTION = 'DUPLICATE_TRANSACTION',
    SUSPICIOUS_TRANSACTION = 'SUSPICIOUS_TRANSACTION',
    OTHER = 'OTHER',
}